<a href="https://www.linkedin.com/in/amit-maindola-51801423/"><img src = "https://cdn-images-1.medium.com/max/1200/1*u16a0WbJeckSdi6kGD3gVA.jpeg" width = 400> </a>
<h1 align="center"><font size=5 color="DE5538">Numpy Basics - Excercises</font></h1>

# Introduction
In this Notebook we will solve the Excersies using NumPy Library.
n; zero is the worst quality and ten is the best quality.

In [2]:
import numpy as np

### Excersise 1
Consider the polynomial expression
\begin{alignat*}
8p(x) {}={} &a_0 &{}+{}& &a_1x &{}+{}& &a_2x^2 &{}+{}& &a_3x^3 .... &{}+{}& &a_nx^n &&&&&& &{}= \sum_{n=0}^{N} &a_n&x^n\\
\end{alignat*}

Write a function p such that p(x, coeff) that computes the value in (1) given a point x and a list of coefficients coeff.

<li> Hint: Use np.cumprod()

In [ ]:
def p(x, coeff):
    X = np.empty(len(coeff))
    X[0], X[1:] = 1, x
    y = np.cumprod(X)
    print(coeff * y)

coef = np.random.randint(low=0, high=10, size=5)
print(coef)
p(5, coef)


### Excersise 2
Generate the Table of 1 to 10 in a columunar fashion

In [79]:
a = np.ones((10), dtype=int) 
b = np.array(np.arange(1,11), dtype=int).reshape(10,1)
c = np.cumsum(a)*b
c.dtype = int
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### Excersise 3
Generate a 10 x 3 array of random number. From each row, pick the column containing the number closest to 0.75  
*Hint:* use of np.abs and np.armin to find the column j that contains the closest element in each row i. The final result should be a vector of Integrers of shape (10,)

In [111]:
arr = np.random.random((10,3))
print(arr)
closest_col = np.argmin(np.abs(arr-0.75), axis=1)
closest_col


[[0.28530691 0.68697086 0.04524872]
 [0.66762252 0.97661143 0.67508277]
 [0.63831747 0.95834441 0.41966958]
 [0.22868162 0.19404806 0.02648442]
 [0.50718932 0.42003594 0.98460329]
 [0.30848386 0.12251038 0.79514185]
 [0.77503167 0.42096067 0.52856504]
 [0.33273032 0.56203884 0.52394371]
 [0.51329606 0.85636007 0.35035946]
 [0.29989255 0.08404929 0.4811527 ]]


array([1, 2, 0, 0, 2, 2, 0, 1, 1, 2], dtype=int64)