<a href="https://www.linkedin.com/in/amit-maindola-51801423/"><img src = "https://cdn-images-1.medium.com/max/1200/1*u16a0WbJeckSdi6kGD3gVA.jpeg" width = 400> </a>
<h1 align="center"><font size=5 color="DE5538">Numpy - Linear Algebra</font></h1>

## Introduction
As we have already got familiar how to use Matrix using NumPy Libraray.  
Let's try our hand to some Linear Algebra

In [2]:
import numpy as np

### Determinant of a Matrix

In [3]:
A = np.matrix('3 1 -3; 1 4 2; -3 2 5')
B = np.matrix('2 -3 4; 5  6 7; 8 9 1')
print("Determinant of matrix \n{} \n==> {}".format(A, np.linalg.det(A)))
print("Determinant of matrix \n{} \n==> {}".format(B, np.linalg.det(B)))

Determinant of matrix 
[[ 3  1 -3]
 [ 1  4  2]
 [-3  2  5]] 
==> -5.000000000000003
Determinant of matrix 
[[ 2 -3  4]
 [ 5  6  7]
 [ 8  9  1]] 
==> -278.99999999999994


### Solve a linear Equation
$$
Ax = b
$$

In [9]:
A = np.matrix('1 1 -1; 0 8 6; -2 4 -6')
b = np.matrix('9;-6;40')
np.linalg.solve(A,b)

matrix([[ 1.],
        [ 3.],
        [-5.]])

### Rank of a Matrix
Calculate the Rank of below Matrices.  
$$
A = 
\begin{bmatrix}
4  & -2 & 6 \\
-2 & 1  & -3
\end{bmatrix}
$$

$$
B=
\begin{bmatrix}
0 & 3 & 5 \\
3 & 5 & 0
\end{bmatrix}
$$

$$
C=
\begin{bmatrix} 
2 & 4 & 8 & 16 \\
16 & 8 & 4 & 0 \\ 
4 & 8 & 16 & 2 \\
2 & 16 & 8 & 4 \\
\end{bmatrix}
$$

$$
D=
\begin{bmatrix} 
5 & -2 & 1 & 0 \\
-2 & 0 & -4 & 1 \\ 
1 & -4 & -11 & 2 \\
0 & 1 & 2 & 0 \\
\end{bmatrix}
$$

In [6]:
A = np.matrix('4 -2 6;-2 1 -3')
B = np.matrix('0 3 5;3 5 0')
C = np.matrix('2 4 8 16;16 8 4 0;4 8 16 2;2 16 8 4')
D = np.matrix('5 -2 1 0;-2 0 -4 1;1 -4 -11 2; 0 1 2 0')
print("Rank of \n{} is {}".format(D, np.linalg.matrix_rank(D)))

Rank of 
[[  5  -2   1   0]
 [ -2   0  -4   1]
 [  1  -4 -11   2]
 [  0   1   2   0]] is 3


In [6]:

print(np.linalg.matrix_rank(B))

2


In [17]:
A = np.matrix('3 1 -3; 1 4 2; -3 2 5')
print(np.linalg.matrix_rank(A))

3


In [4]:
A = np.matrix('1 3 4; -4 2 -6; -3 -2 -7')
np.linalg.det(A)

0.0

#### Leontif's Input Output Model
Find a Matrix **p** which satify the below equation 
$$Ap = p\\$$
$$
\begin{bmatrix}
0.1&0.5&0\\
0.8&0&0.4\\
0.1&0.5&0.6\\
\end{bmatrix}*\begin{bmatrix}
p1\\
p2\\
p3\\
\end{bmatrix} 
 = 
\begin{bmatrix}
p1\\
p2\\
p3\\
\end{bmatrix} 
$$

In [15]:
A = np.matrix('0.1 0.5 0; 0.8 0 0.4; 0.1 0.5 0.6')
b = np.matrix('0.4;0.72;1.0')
A*b

matrix([[0.4 ],
        [0.72],
        [1.  ]])