<a href="https://www.linkedin.com/in/amit-maindola-51801423/"><img src = "https://cdn-images-1.medium.com/max/1200/1*u16a0WbJeckSdi6kGD3gVA.jpeg" width = 400> </a>
<h1 align="center"><font size=5 color="DE5538">Matrix - Basic Operation</font></h1>

## Introduction
In this Notebook we will see some more operation on the Numpy

In [3]:
### Import the Libraries
import numpy as np

In [5]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = np.array([99, 99, 99])

In [7]:
np.concatenate([x,y,z])

array([ 1,  2,  3, 10, 20, 30, 99, 99, 99])

#### Perform two dim concatenation

In [8]:
two_d_array = np.array([[1, 2, 3], [4, 5,6]])
np.concatenate([two_d_array, two_d_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.vstack([two_d_array,y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [12]:
np.hstack([two_d_array, np.array([[10],[20]])])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

### Comparison between ufunc and loops
Now's let's compare the performance of ufunc provided by Numpy against the Looping in Python

In [19]:
# Let's create an array of 5000 elements
barray = np.random.randint(1, 100, size=5000)
barray.reshape(100,50)

array([[85, 15, 37, ..., 25, 42, 39],
       [64, 10,  1, ..., 59, 43, 71],
       [50, 41, 73, ..., 68, 24, 79],
       ...,
       [77, 21, 66, ..., 58, 32, 37],
       [96, 95, 13, ..., 13, 51,  5],
       [72, 52, 65, ..., 39, 93, 86]])

In [21]:
def find_inverse(array):
    inverse_list = []
    for number in array:
        inverse_list.append(1/number)
    return inverse_list

In [22]:
%timeit find_inverse(barray)

1.24 ms ± 21.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%timeit (1/barray)

8.75 µs ± 165 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Boolean Utilities

In [25]:
x = np.random.randint(10, size=(3,4))
x

array([[9, 2, 6, 5],
       [3, 6, 1, 0],
       [4, 5, 4, 5]])

In [31]:
np.any(x > 8, axis=0)

array([ True, False, False, False])

In [35]:
np.all(x>=2, axis=0)

array([ True,  True, False, False])